# Generated by Django 4.2.6 on 2023-11-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='heading',
            field=models.CharField(default='Entry Name', max_length=200),
            preserve_default=False,
        ),
    ]
